config/routes.rb
Rails.application.routes.draw do
  # get 'games/index'
  root to: "games#index"
  resources :games, only: [:index]

  # ルーティングはすべてのビュー作成後に繋げる(モデル整理のため)
  # ヴァンガードページのルートを設定
  get '/vanguardes', to: 'vanguardes#index'

  # resources :Vanguard
  # resources :Vanguard ギフト
  # resources :Vanguard Dress
  resources :divines

  # バトスピページのルートを設定
  # ホームページからbattlespiritsページに遷移するルーティング
  # get '/battlespirits', to: 'battlespirits#index', as: 'game_battlespirits'
  resources :battlespirits

  # 色ごとのデッキ作成ページに遷移
  # get '/battlespirits/red', to: 'red#index', as:'battlespirits_red'
  # resources :battlespirits, only: [:index] do
  #   resources :red, only: [:index, :new, :create, :show]
  # end

  # battlespiritsとredのidを1に指定してルーティングを繋げている、battlespiritsがroom、redがwordとして考えればidを指定しなくても繋げられそう
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/battlespirit.rb
class Battlespirit < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :color

  #空の投稿を保存できないようにする
  validates :deck_name,  presence: true

  #ジャンルの選択が「---」の時は保存できないようにする
  validates :color_id, numericality: { other_than: 1 , message: "can't be blank"}
end

app/models/card_count.rb
class CardCount < ActiveHash::Base
  self.data = [
    { id: 1, label: '0枚' },
    { id: 2, label: '1枚' },
    { id: 3, label: '2枚' },
    { id: 4, label: '3枚' }
  ]
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '赤' },
    { id: 3, name: '青' },
    { id: 4, name: '黄' },
    { id: 5, name: '緑' },
    { id: 6, name: '白' },
    { id: 7, name: '紫' },
  ]

  include ActiveHash::Associations
  has_many :battlespirits
end

app/models/divine.rb
class Divine < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/battlespirits_controller.rb
class BattlespiritsController < ApplicationController
  def index 
    show_color_names
    @battlespirits = Battlespirit.all
  end
  
  def new
    # 新しいBattlespiritsオブジェクトを作成
    @battlespirits = Battlespirit.new
  end
  
  def create
    @battlespirits = Battlespirit.new(battlespirits_params)
    if @battlespirits.save
      redirect_to battlespirits_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @battlespirits = Battlespirit.find(params[:id])
  end

  def edit
    @battlespirits = Battlespirit.find(params[:id])
  end

  def update
    battlespirits = Battlespirit.find(params[:id])
    battlespirits.update(battlespirits_params)
    redirect_to battlespirits_path
  end

  def destroy
    battlespirits = Battlespirit.find(params[:id])
    battlespirits.destroy
    redirect_to battlespirits_path
  end

  private
  def battlespirits_params
    params.require(:battlespirit).permit(:deck_name, :color_id, :ultimate1, :ultimate2, :ultimate3, :ultimate4, :spirit1, :spirit2, :spirit3, :spirit4, :brave1, :brave2, :brave3, :brave4, :magic1, :magic2, :magic3, :magic4, :nexus1, :nexus2, :nexus3, :nexus4)
  end

  def show_color_names
    @color2 = Color.find_by_id(2)
    @color3 = Color.find_by_id(3)
    @color4 = Color.find_by_id(4)
    @color5 = Color.find_by_id(5)
    @color6 = Color.find_by_id(6)
    @color7 = Color.find_by_id(7)
  end
end

app/controllers/divines_controller.rb
class DivinesController < ApplicationController
  def index
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index #トップページを表示
  end
end

app/controllers/red_controller.rb
class RedController < ApplicationController
  def index
    # デッキの一覧を表示する処理
    @red = Red.find_by(params[:deck_name])
    # @battlespirits = battlespirits.find(params[:battlespirits_id])
  end

  def new
    # 新しいデッキを作成するフォームを表示する処理
    @red = Red.new
  end

  def create
    # 作成したデッキを保存する処理
    
    # 合計枚数が40枚未満だったら保存できない処理
  end

  def show
    @red = Red.find_by(params[:id])
    # @battlespirits = battlespirits.find(params[:battlespirits_id])
  end

  private
  def red_params
    params.require(:red).permit(:deck_name, :ultimate1, :ultimate2, :ultimate3, :ultimate4, :spirit1, :spirit2, :spirit3, :spirit4, :brave1, :brave2, :brave3, :brave4, :magic1, :magic2, :magic3, :magic4, :nexus1, :nexus2, :nexus3, :nexus4).merge(:battlespirits_id)
  end
end

app/controllers/vanguardes_controller.rb
class VanguardesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battlespirits_helper.rb
module BattlespiritsHelper
end

app/helpers/color_helper.rb
module ColorHelper
end

app/helpers/deckes_helper.rb
module DeckesHelper
end

app/helpers/divines_helper.rb
module DivinesHelper
end

app/helpers/vanguardes_helper.rb
module VanguardesHelper
end

app/views/battlespirits/edit.html.erb
<%# タイトルをクリックするとトップページに戻る %>
<div class="deck-header">
  <div class="left-header">
    デッキレシピ
  </div>
</div>

<div class="mains">
  <%= form_with model: @battlespirits, class: 'form', local: true do |f| %>
    <%# デッキ名を記入 %>
    <div class= "deck">
      <div class="deck-name">
        <div class="category">
          デッキ名 
        </div>
        <div class="names">
          <%= f.text_field :deck_name, class: 'form-detail', placeholder: 'デッキ名' %>
        </div>
      </div>
      <div class="color_selection">
        色選択
        <%# ActiveHashで色を選択 %>
        <%= f.collection_select(:color_id, Color.all, :id, :name, {}, {class:"color-select"}) %>
      </div>
    </div>

    <%# カテゴリの横にカード名を入力 %>
    <%# 左側のリストの枚数が表示されていない %>
    <div class="deck">
      <div class="category">
        アルティメット  
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :ultimate1, class: 'form-detail', placeholder: 'アルティメット' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :ultimate2, class: 'form-detail', placeholder: 'アルティメット' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :ultimate3, class: 'form-detail', placeholder: 'アルティメット' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :ultimate4, class: 'form-detail', placeholder: 'アルティメット' %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        スピリット
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :spirit1, class: 'form-detail', placeholder: 'スピリット' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :spirit2, class: 'form-detail', placeholder: 'スピリット' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :spirit3, class: 'form-detail', placeholder: 'スピリット' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :spirit4, class: 'form-detail', placeholder: 'スピリット' %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        ブレイブ 
        <%# ブレイブは3~4枚がベストなバランスかも、スピリットの入力フォームを増やす必要がある %>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :brave1, class: 'form-detail', placeholder: 'ブレイブ' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :brave2, class: 'form-detail', placeholder: 'ブレイブ' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :brave3, class: 'form-detail', placeholder: 'ブレイブ' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :brave4, class: 'form-detail', placeholder: 'ブレイブ' %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        マジック
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :magic1, class: 'form-detail', placeholder: 'マジック' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :magic2, class: 'form-detail', placeholder: 'マジック' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :magic3, class: 'form-detail', placeholder: 'マジック' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :magic4, class: 'form-detail', placeholder: 'マジック' %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        ネクサス
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :nexus1, class: 'form-detail', placeholder: 'ネクサス' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :nexus2, class: 'form-detail', placeholder: 'ネクサス' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :nexus3, class: 'form-detail', placeholder: 'ネクサス' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :nexus4, class: 'form-detail', placeholder: 'ネクサス' %> :  3枚
        </div>
      </div>
    </div>

    <div class="total">
      合計: 40枚
    </div>

    <div class="post-btn-contents">
      <div class="form-submit">
        <%# 保存 %>
        <%= f.submit '保存', class: 'form-submit' %>
      </div>
      <div class="back-btn">
        <%# 戻る %>
        <%=link_to '戻る', battlespirit_path, class:"back-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/battlespirits/index.html.erb
<%# タイトルをクリックするとトップページに戻る %>
<div class="deck-header">
  <div class="left-header">
    デッキレシピ
  </div>
  <div class="right-header">
    <%= link_to "新規作成", new_battlespirit_path %>
  </div>
</div>

<%# バトスピの色選択ページ 　css設定済%>
<div class="mains">
  <div class="main">
    <div class="colors">
      <%# 色ごとのデッキ作成ページに遷移 %>
      <div class="color">
        <div class="red">
          赤
        </div>
        <div class="decks">
          <!-- battlespirits リストの各要素に対して処理を行う -->
          <% @battlespirits.each do |battlespirit| %>
            <div class="deck_list">
              <div class="deck">
               <!-- 色が2の場合、デッキ名を表示 -->
               <%= battlespirit.deck_name if battlespirit.color_id == 2 %>
              </div>

              <!-- 色が2の場合にのみ詳細へのリンクを表示 -->
              <% if battlespirit.color_id == 2 %>
                <div class= "more">
                  <ul class="more_list">
                    <li>
                      <!-- battlespirit の詳細ページへのリンク -->
                      <%= link_to '詳細', battlespirit_path(battlespirit.id) %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="colors">
      <%# 色ごとのデッキ作成ページに遷移 %>
      <div class="color">
        <div class="blue">
          青
        </div>
        <div class="decks">
          <!-- battlespirits リストの各要素に対して処理を行う -->
          <% @battlespirits.each do |battlespirit| %>
            <div class="deck_list">
              <div class="deck">
                <!-- 色が2の場合、デッキ名を表示 -->
                <%= battlespirit.deck_name if battlespirit.color_id == 3 %>
              </div>

              <!-- 色が3の場合にのみ詳細へのリンクを表示 -->
              <% if battlespirit.color_id == 3 %>
                <div class= "more">
                  <ul class="more_list">
                    <li>
                      <!-- battlespirit の詳細ページへのリンク -->
                      <%= link_to '詳細', battlespirit_path(battlespirit.id) %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="main">
    <div class="colors">
      <%# 色ごとのデッキ作成ページに遷移 %>
      <div class="color">
        <div class="yellow">
          黄
        </div>
        <div class="decks">
          <!-- battlespirits リストの各要素に対して処理を行う -->
          <% @battlespirits.each do |battlespirit| %>
            <div class="deck_list">
              <div class="deck">
                <!-- 色が4の場合、デッキ名を表示 -->
                <%= battlespirit.deck_name if battlespirit.color_id == 4 %>
              </div>

              <!-- 色が4の場合にのみ詳細へのリンクを表示 -->
              <% if battlespirit.color_id == 4 %>
                <div class= "more">
                  <ul class="more_list">
                    <li>
                      <!-- battlespirit の詳細ページへのリンク -->
                      <%= link_to '詳細', battlespirit_path(battlespirit.id) %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="colors">
      <%# 色ごとのデッキ作成ページに遷移 %>
      <div class="color">
        <div class="green">
          緑
        </div>
        <div class="decks">
          <!-- battlespirits リストの各要素に対して処理を行う -->
          <% @battlespirits.each do |battlespirit| %>
            <div class="deck_list">
              <div class="deck">
                <!-- 色が5の場合、デッキ名を表示 -->
                <%= battlespirit.deck_name if battlespirit.color_id == 5 %>
              </div>

              <!-- 色が5の場合にのみ詳細へのリンクを表示 -->
              <% if battlespirit.color_id == 5 %>
                <div class= "more">
                  <ul class="more_list">
                    <li>
                      <!-- battlespirit の詳細ページへのリンク -->
                      <%= link_to '詳細', battlespirit_path(battlespirit.id) %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="main">
    <div class="colors">
      <%# 色ごとのデッキ作成ページに遷移 %>
      <div class="color">
        <div class="white">
          白
        </div>
        <div class="decks">
          <!-- battlespirits リストの各要素に対して処理を行う -->
          <% @battlespirits.each do |battlespirit| %>
            <div class="deck_list">
              <div class="deck">
                <!-- 色が6の場合、デッキ名を表示 -->
                <%= battlespirit.deck_name if battlespirit.color_id == 6 %>
              </div>

              <!-- 色が6の場合にのみ詳細へのリンクを表示 -->
              <% if battlespirit.color_id == 6 %>
                <div class= "more">
                  <ul class="more_list">
                    <li>
                      <!-- battlespirit の詳細ページへのリンク -->
                      <%= link_to '詳細', battlespirit_path(battlespirit.id) %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="colors">
      <%# 色ごとのデッキ作成ページに遷移 %>
      <div class="color">
        <div class="purple">
          紫
        </div>
        <div class="decks">
          <!-- battlespirits リストの各要素に対して処理を行う -->
          <% @battlespirits.each do |battlespirit| %>
            <div class="deck_list">
              <div class="deck">
              <!-- 色が7の場合、デッキ名を表示 -->
                <%= battlespirit.deck_name if battlespirit.color_id == 7 %>
              </div>

              <!-- 色が7の場合にのみ詳細へのリンクを表示 -->
              <% if battlespirit.color_id == 7 %>
                <div class= "more">
                  <ul class="more_list">
                    <li>
                      <!-- battlespirit の詳細ページへのリンク -->
                      <%= link_to '詳細', battlespirit_path(battlespirit.id) %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/battlespirits/show.html.erb
<%# タイトルをクリックするとトップページに戻る %>
<div class="deck-header">
  <div class="left-header">
    デッキレシピ
  </div>
  <div class="right-header">
    <!-- 投稿した内容を修正する -->
    <ul class="more_list">
      <li>
        <%# 編集 %>
        <%= link_to '編集', edit_battlespirit_path(@battlespirits), class: "deck-blue-btn" %> 
      </li>
      <li>
        <%=link_to '戻る', battlespirits_path, class:"back-btn" %>
      </li>
      <li>
        <%= link_to '削除', battlespirit_path(@battlespirits), data: { turbo_method: :delete }, method: :delete, class:"deck-blue-btn" %>
      </li>
    </ul>
  </div>
</div>

<%# デッキ作成  cardを縦横2列にし「カード名：3枚」の形で保存、枚数はActiveHashで表記%>
<div class="mains">
  <%# デッキ名を記入 %>
    <div class= "deck">
      <div class="deck-name">
        <div class="category">
          デッキ名 
        </div>
        <div class="names">
          <%= @battlespirits.deck_name %>
        </div>
      </div>
      <div class="color_selection">
        <%= @battlespirits.color.name %>
      </div>
    </div>

    <%# カテゴリの横にカード名を入力 %>
    <div class="deck">
      <div class="category">
        アルティメット  
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.ultimate1 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.ultimate2 %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.ultimate3 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.ultimate4 %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        スピリット
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.spirit1 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.spirit2 %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.spirit3 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.spirit4 %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        ブレイブ 
        <%# ブレイブは3~4枚がベストなバランスかも、スピリットの入力フォームを増やす必要がある %>
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.brave1 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.brave2 %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.brave3 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.brave4 %>
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        マジック
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.magic1 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.magic2 %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.magic3 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.magic4 %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        ネクサス
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.nexus1 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.nexus2 %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= @battlespirits.nexus3 %> :  3枚
        </div>
        <div class="card">
          <%= @battlespirits.nexus4 %> :  3枚
        </div>
      </div>
    </div>

    <div class="total">
      合計: 40枚
    </div>
</div>

app/views/clan/vanguard.html.erb
<%# タイトルをクリックするとトップページに戻る %>
<div class="header">
  デッキレシピ
</div>

<%# 国家 %>
<div class="worlds">
  <%# ユナイテッドサンクチュアリのクランページに遷移 %>
  <div class="world">
    ユナイテッドサンクチュアリ
  </div>
  <%# ドラゴンエンパイアのクランページに遷移 %>
  <div class="world">
    ドラゴンエンパイア
  </div>
  <%# ズーのクランページに遷移 %>
  <div class="world">
    ズー
  </div>
  <%# スターゲートのクランページに遷移 %>
  <div class="world">
    スターゲート
  </div>
  <%# ダークゾーンのクランページに遷移 %>
  <div class="world">
    ダークゾーン
  </div>
  <%# メガラニカのクランページに遷移 %>
  <div class="world">
    メガラニカ
  </div>
</div>

app/views/color/_red.html.erb
<%# タイトルをクリックするとトップページに戻る %>
<div class="deck-header">
  <div class="left-header">
    デッキレシピ
  </div>
  <div class="right-header">
    新規作成
  </div>
</div>

<%# デッキ一覧を表示をeachで表示、詳細を選択でデッキ一覧を表示、編集と削除%>
<div class="decks">
  <div class="deck">
    ストライク・アポロ合体デッキ
  </div>
</div>

app/views/divines/index.html.erb
<%# タイトルをクリックするとトップページに戻る %>
<div class="header">
  デッキレシピ
</div>

app/views/games/index.html.erb
<%# タイトルをクリックするとトップページに戻る %>
<div class="header">
    デッキレシピ
    <%# <h1 class="logo"><a href="index.html">APP FIRST</a></h1> %>
</div>

<%# カードゲーム選択 %>
<div class="games">
  <%# ヴァンガード %>
  <ul class="game">
    <%# ヴァンガードのルール選択ページに遷移(vanguardフォルダのindex.html.erbへ)%>
    
    <%= link_to "Vanguard", vanguardes_path %>
    <%# <li class="game-list"><a href="service.html">SERVICE</a></li> %>
  </ul>

  <%# バトスピ %>
  <ul class="game">
    <%# バトスピの色選択ページに遷移(battlespiritsフォルダのindex.html.erbへ)%>
    <%# Battle Spirits %>
    <%# <li class="game-list"><a href="/battlespiritses">Battle Spirits</a></li> %>
    <%= link_to "Battle Spirits", battlespirits_path %>
  </ul>

</div>

app/views/red/edit.html.erb
<%# タイトルをクリックするとトップページに戻る %>
<div class="deck-header">
  <div class="left-header">
    デッキレシピ
  </div>
</div>

<div class="mains">
  <%= form_with model: @battlespirits, class: 'form', local: true do |f| %>
    <%# デッキ名を記入 %>
    <div class= "deck">
      <div class="deck-name">
        <div class="category">
          デッキ名 
        </div>
        <div class="names">
          <%= f.text_field :deck_name, class: 'form-detail', placeholder: 'デッキ名' %>
        </div>
      </div>
      <div class="color_selection">
        色選択
        <%# ActiveHashで色を選択 %>
        <%= f.collection_select(:color_id, Color.all, :id, :name, {}, {class:"color-select"}) %>
      </div>
    </div>

    <%# カテゴリの横にカード名を入力 %>
    <div class="deck">
      <div class="category">
        アルティメット  
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :ultimate1, class: 'form-detail', placeholder: 'アルティメット' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :ultimate2, class: 'form-detail', placeholder: 'アルティメット' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :ultimate3, class: 'form-detail', placeholder: 'アルティメット' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :ultimate4, class: 'form-detail', placeholder: 'アルティメット' %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        スピリット
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :spirit1, class: 'form-detail', placeholder: 'スピリット' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :spirit2, class: 'form-detail', placeholder: 'スピリット' %> :  3枚
        </div>
      </div>
      <div class="cards">
          <%= f.text_field :spirit3, class: 'form-detail', placeholder: 'スピリット' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :spirit4, class: 'form-detail', placeholder: 'スピリット' %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        ブレイブ 
        <%# ブレイブは3~4枚がベストなバランスかも、スピリットの入力フォームを増やす必要がある %>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :brave1, class: 'form-detail', placeholder: 'ブレイブ' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :brave2, class: 'form-detail', placeholder: 'ブレイブ' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :brave3, class: 'form-detail', placeholder: 'ブレイブ' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :brave4, class: 'form-detail', placeholder: 'ブレイブ' %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        マジック
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :magic1, class: 'form-detail', placeholder: 'マジック' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :magic2, class: 'form-detail', placeholder: 'マジック' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :magic3, class: 'form-detail', placeholder: 'マジック' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :magic4, class: 'form-detail', placeholder: 'マジック' %> :  3枚
        </div>
      </div>
    </div>

    <div class="deck">
      <div class="category">
        ネクサス
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :nexus1, class: 'form-detail', placeholder: 'ネクサス' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :nexus2, class: 'form-detail', placeholder: 'ネクサス' %> :  3枚
        </div>
      </div>
      <div class="cards">
        <div class="card">
          <%= f.text_field :nexus3, class: 'form-detail', placeholder: 'ネクサス' %> :  3枚
        </div>
        <div class="card">
          <%= f.text_field :nexus4, class: 'form-detail', placeholder: 'ネクサス' %> :  3枚
        </div>
      </div>
    </div>

    <div class="total">
      合計: 40枚
    </div>

    <div class="post-btn-contents">
      <div class="form-submit">
        <%# 保存 %>
        <%= f.submit '保存', class: 'form-submit' %>
      </div>
      <div class="back-btn">
        <%# 戻る %>
        <%=link_to '戻る', battlespirit_path, class:"back-btn" %>
      </div>
    </div>
  <% end %>
</div>